### ISSUE TITLE
nicht konforme CSS IDs im Beispiel Modul

### ISSUE THREAD

**Issue by tyrant88** [olien/glossar#7]
in ```glossar_listenansicht_modulausgabe.php``` hast du Leerzeichen in der ID
```<p id="character B">B</p>```  im dazugehörigen Link natürlich auch.

**Comment by tyrant88** [comment]
ansonsten Danke für das Modul, hat mir ne halbe Stunde Arbeit gespart...

**Comment by olien** [comment]
Danke. Hatte mich nicht mehr damit beschäftigt. Aus Gründen: https://github.com/FriendsOfREDAXO/multiglossar
